In [3]:
import numpy as np

# 1D Array from a Python list
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Built-in Array Generators
zeros = np.zeros((3, 3))       # 3x3 matrix of 0s
ones = np.ones((2, 4))         # 2x4 matrix of 1s
ranged = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8] (start, stop, step)
linear = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1

# Inspecting Array Attributes
print("Shape:", arr_2d.shape)  # (2, 3) -> 2 rows, 3 columns
print("Dimensions:", arr_2d.ndim)  # 2
print("Data Type:", arr_2d.dtype)  # e.g., int64

Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [6]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
# Standard Slicing -> array[start:stop:step]
print(arr[1:4])

[20 30 40]


In [7]:
# 2D Slicing -> matrix[row_slice, col_slice]
print(matrix[0:2,1:3])

[[20 30]
 [50 60]]


In [8]:
# Boolean Indexing (Filtering)
data = np.array([12,46,7,89,23,56])
mask=data>30
print(data[mask])

[46 89 56]


In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([10,20,30])
print(a+b)
print(a-b)
print(b**2)
print(a*b)

[11 22 33]
[ -9 -18 -27]
[100 400 900]
[10 40 90]


In [15]:
# Matrix Multiplication (Dot Product)
n1=np.array([[1,2],[3,4]])
n2=np.array([[5,6],[7,8]])
print(np.dot(n1,n2))


[[19 22]
 [43 50]]


In [16]:
# Useful Aggregations
scores=np.array([[80,90],[70,85],[95,100]])
print("Total sum:",np.sum(scores))
print("Column-wise Mean(axis=0):",np.mean(scores,axis=0))
print("Row-wise Max(axis=1):",np.max(scores,axis=1))

Total sum: 520
Column-wise Mean(axis=0): [81.66666667 91.66666667]
Row-wise Max(axis=1): [ 90  85 100]


Day 3 Completed

Topics Covered:
- NumPy Arrays
- Indexing & Slicing
- Boolean Indexing
- Mathematical Operations
- Matrix Multiplication
- Aggregation Functions

Outcome:
Successfully learned NumPy fundamentals and completed array-based calculations.